### ISSUE TITLE
override_special parameter for random_password doesn't work correctly. 

### ISSUE THREAD

**Issue by yury-stsefanovich** [hashicorp/terraform-provider-random#341]
### Terraform CLI and Provider Versions

Terraform v1.3.3
+ provider registry.terraform.io/hashicorp/aws v4.37.0
+ provider registry.terraform.io/hashicorp/random v3.4.3

### Terraform Configuration

```terraform
resource "random_password" "db_pass" {
  length           = 16
  special          = true
  min_special      = 5
  override_special = "!#$%^&*()-_=+[]{}<>:?"
  keepers = {
    pass_version = 1
  }
}
```

### Expected Behavior

random_password.db_tst_pas.result contains specials only from [!#$%^&*()-_=+[]{}<>:?] list.

### Actual Behavior

random_password.db_tst_pas.result contains specials like `\`, `/`

For example, result = "}$4Z[IXN[*{#=\u0026:q".
Apply successful, but login to db doesn't work because of `\` character in the password. 

### Steps to Reproduce

1. `terraform apply`

### How much impact is this issue causing?

Low

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bendbennett** [comment]
@yury-stsefanovich it seems likely that you are describing the same behaviour as documented in this [issue](https://github.com/hashicorp/terraform-provider-random/issues/337).

`&<>` are [encoded in the state file](https://github.com/hashicorp/terraform-provider-random/issues/337#issuecomment-1331978936).

In the example that you provided I believe that the password (result) that you generated is `}$4Z[IXN[*{#=&:q`. 

Can you confirm whether using `&` instead of `\u0026` in your DB login works as expected?

**Comment by yury-stsefanovich** [comment]
Hi @bendbennett, thanks for such quick response. 
Yes, confirmed that & works. 
So, characters "<", ">", "&" just encoded in json. 

Thanks for help!
