### ISSUE TITLE
Resource 'snowflake_grant_privileges_to_role' marks 'priveleges' attribute as changed regardless of any changes being made

### ISSUE THREAD

**Issue by ToxicCypher** [hashicorp/terraform-provider-random#503]
### Terraform CLI and Provider Versions

```
terraform {
  required_version = ">= 1.3.0"
  required_providers {
    snowflake = {
      source  = "Snowflake-Labs/snowflake"
      version = "0.80.0"
    }
  }
}
```

### Terraform Configuration

```terraform
//main.tf

# Resource Monitor w/ Parametrized Values
resource "snowflake_resource_monitor" "my_resource_monitor" {
  name                      = "MY_RESOURCE_MONITOR"
  credit_quota              = var.my_resource_monitor_credit_quota
  frequency                 = var.my_resource_monitor_frequency
  start_timestamp           = var.my_resource_monitor_start_timestamp
  end_timestamp             = var.my_resource_monitor_end_timestamp
  notify_triggers           = var.my_resource_monitor_notify_triggers
  suspend_trigger           = var.my_resource_monitor_suspend_trigger
  suspend_immediate_trigger = var.my_resource_monitor_suspend_immediate_trigger
  set_for_account           = var.my_resource_monitor_set_for_account
  notify_users              = var.my_resource_monitor_notify_users
  warehouses                = var.my_resource_monitor_warehouses
}

resource "snowflake_grant_privileges_to_role" "my_resource_monitor-grant" {
  depends_on = [snowflake_resource_monitor.my_resource_monitor]

  # Map(Object) of grant information where the key is the role name.
  for_each = var.my_resource_monitor_grants

  privileges = each.value.my_resource_monitor_privileges
  role_name  = each.key
  on_account_object {
    object_type = var.object_type # "RESOURCE MONITOR"
    object_name = snowflake_resource_monitor.my_resource_monitor.name
  }
  with_grant_option = each.value.my_resource_monitor_with_grant_option
}
```

### Expected Behavior

The ```privileges``` parameter of the snowflake_grant_privileges_to_role should only be marked as changed when the list of priveleges has been altered.

### Actual Behavior

The ```privileges``` parameter of the snowflake_grant_privileges_to_role is marked as changed, regardless of any changes being made to the ```privileges``` parameter.

This image depicts 82 warehouse grant changes that were not actually changed - terraform plan output. terraform apply runs fine.
![image](https://github.com/hashicorp/terraform-provider-random/assets/129532051/e26b7b6c-8f49-427f-8c1f-8113dbad9fd1)

### Steps to Reproduce

1. `terraform plan`
2. `terraform apply`

### How much impact is this issue causing?

Medium

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bflad** [comment]
Hi @ToxicCypher 👋 Thank you for raising this and sorry you are running into trouble.

This issue tracker is for the [`hashicorp/random` provider](https://registry.terraform.io/providers/hashicorp/random/latest), which does not appear in your bug report. The [`Snowflake-Labs/snowflake` provider](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest) mentioned in your bug report has an issue tracker available at (found via the "Source Code" link in the Registry): https://github.com/Snowflake-Labs/terraform-provider-snowflake and it looks like you already filed https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/2281 there.

Since this does not appear to be an issue with this provider codebase, I'm going to close this issue.
