### ISSUE TITLE
random_integer returns string?

### ISSUE THREAD

**Issue by dbogen** [hashicorp/terraform-provider-random#59]
It looks like `random_integer` is returning a string, rather than an integer.

### Terraform Version
Terraform v0.11.13
+ provider.random v2.1.1

### Affected Resource(s)
- random_integer

### Terraform Configuration Files
```
provider "random" {
  version = ">= 1"
}

resource "random_integer" "foo" {
  min = 1
  max = 99999
}

locals {
  bar_int = "bar-${format("%05d",random_integer.foo.result)}"
  bar_str = "bar-${format("%05s",random_integer.foo.result)}"
}

output "foobar-int" {
  value       = "${local.bar_int}"
}

output "foobar-str" {
  value       = "${local.bar_str}"
}
```

### Debug Output
https://gist.github.com/dbogen/799b4253bc459098122058066d930b9c

### Expected Behavior
```
Outputs:

foobar-int = bar-00112
foobar-str = bar-%!s(integer=00112)
```

### Actual Behavior
```
Outputs:

foobar-int = bar-%!d(string=00112)
foobar-str = bar-00112
```

### Steps to Reproduce
1. `terraform init`
1. `terraform apply`

**Comment by apparentlymart** [comment]
Hi @dbogen,

This is an unfortunate quirk of Terraform v0.11 and earlier: all provider results are either strings, lists of strings, or maps of strings. The _bug_ here is that `format` should see that you used `%d` and automatically try to convert the string result to an integer, as all other language features do, but instead (because in v0.11 `format` is based on Go's formatter) it leaves it as a string but produces invalid output.

This is fixed in both regards in the `master` branch of Terraform, in preparation for the forthcoming v0.12.0 release:

* Providers now return full type information for their attributes, allowing Terraform Core to see that the result of `random_integer` is a number rather than a string.
* The `format` function is no longer based on Go's own `fmt` package and instead is a custom implementation that understands how to do all of the standard type conversions used in the Terraform language, so that `%d` can be used with strings containing decimal digits just as is the case for arithmetic operators on strings, etc.

The `random` provider won't need to change at all to benefit from this when running in v0.12.0 mode, except to support the new v0.12.0 plugin protocol. The latest version of this provider is already compatible, so no further changes are required here for it to work. The example you tried here should therefore work as expected in [v0.12.0-beta1](https://www.hashicorp.com/blog/announcing-terraform-0-1-2-beta1) and in the forthcoming v0.12.0 release, without any further changes.

To work around this in Terraform v0.11, I'd suggest performing some no-op arithmetic on the result to force the language to convert to integer. For example:

```hcl
  bar_int = "bar-${format("%05d", floor(random_integer.foo.result))}"
```

Although that will no longer be necessary in Terraform v0.12.0, that additional `floor` function won't do any harm there, and so this workaround shouldn't cause any compatibility difficulties during upgrade, allowing you to remove it at your leisure after upgrading.

**Comment by kmoe** [comment]
This works as expected in Terraform 0.12 and above.
