### ISSUE TITLE
random_uuid with keepers doesn't respect depends_on

### ISSUE THREAD

**Issue by ocervell** [hashicorp/terraform-provider-random#95]
Hi there,

I'm encountering a bug when trying to generate a file and then use `keepers` to generate a unique uuid updated based on the `filemd5` hashes of the files within a directory. 

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.
```
Terraform v0.12.13
+ provider.archive v1.3.0
+ provider.google v2.19.0
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.random v2.2.1
```

### Affected Resource(s)
Please list the resources as a list, for example:
- `random_uuid`
If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "local_file" "generated-config" {
  content  = jsonencode({a=1, b=2})
  filename = "${path.module}/code/generated.json"
}

resource "random_uuid" "code_hash" {
  keepers = {
    for filename in fileset("${path.module}/code", "**/*") :
    filename => filemd5("${path.module}/code}/${filename}")
  }
  depends_on = [
    local_file.generated-config
  ]
}
```

### Debug Output
```
Error: Provider produced inconsistent final plan

When expanding the plan for
module.slo-pipeline-cf-errors.random_uuid.code_hash to include new values
learned so far during apply, provider "random" produced an invalid new value
for .keepers["slo_config.json"]: was
cty.StringVal("d41d8cd98f00b204e9800998ecf8427e"), but now
cty.StringVal("4fd65632594f3361802ed49a5f5f6bf0").


This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?
The content of `keepers` including the `fileset` should have been evaluated **after** the file is dropped in the directory.

### Actual Behavior
What actually happened?
The provider produced an inconsistent plan. It seems that `fileset` was evaluated before the `local_file` resource was run, even if `depends_on` is specified.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by bflad** [comment]
Hi folks 👋 Thank you for raising this issue and sorry for the frustrating behavior.

While the error messaging here is less than ideal, its unfortunately an issue that cannot be easily be resolved with this (or any provider) when dealing with a configuration setup in this manner. In the Terraform configuration language, functions such as `fileset()` and `filemd5()` are evaluated during configuration parsing, rather than participating in the graph. The [current `fileset()` documentation](https://developer.hashicorp.com/terraform/language/functions/fileset) notes this behavior with this statement:

> Functions are evaluated during configuration parsing rather than at apply time, so this function can only be used with files that are already present on disk before Terraform takes any actions.

Therefore it is invalid to use these configuration functions for this exact setup, since it generally will cause Terraform's planned value to differ from the applied value (the `random_uuid` resource being the unfortunate receiver of that difference in this case).

The good news though is that there could be a configuration-based change that should help resolve the issue. If all the desired files are managed by the `local_file` resource, the [`content_md5` attribute](https://registry.terraform.io/providers/hashicorp/local/latest/docs/resources/file#content_md5) will always reflect any planned changes.

For example:

```terraform
terraform {
  required_providers {
    local = {
      source  = "hashicorp/local"
      version = "2.4.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "3.5.1"
    }
  }
}

resource "local_file" "example" {
  count = 3

  content  = jsonencode({ index = count.index })
  filename = "example${count.index}.json"
}

resource "random_uuid" "example" {
  keepers = {
    for file in local_file.example[*] :
    file.filename => file.content_md5
  }
}
```

If there are files outside those being managed by the `local_file` resource(s), then it might be worth either referencing those via the [`local_file` data source](https://registry.terraform.io/providers/hashicorp/local/latest/docs/data-sources/file) or [creating an issue with the local provider](https://github.com/hashicorp/terraform-provider-local/issues) to consider supporting a data source which operates similar to `fileset()` and can correctly participate in the Terraform graph.

Since there is nothing that can be changed in this provider for this situation, I'm going to close this issue. If you have further questions about how to setup your configuration, please raise a new topic in [HashiCorp Discuss](https://discuss.hashicorp.com/c/terraform-core/27). Thanks.
